### ISSUE TITLE
自动钓鱼老师卡在等待抛竿

### ISSUE THREAD

**Issue by DeMoNsI** [wkgcass/hotta-pc-assistant#3]
大佬你B站视频被删了，再发一个，自动钓鱼老是卡在等待抛竿

**Comment by wkgcass** [comment]
视频刚删那天就重发了。  
等待抛竿是因为没检测到绿点。建议调大分辨率，选择的时候对准点位。茵纳斯绿点在水下，水面上只有细线，所以需要离得近一点。  
或者加群用最新的测试版，对茵纳斯钓鱼的支持更好，也支持不检测绿点直接钓鱼
---
我准备2.6蕾比利亚出来之后再在github发新的release的，这之前先在群里拿测试版吧

**Comment by DeMoNsI** [comment]
好的，感谢回复

**Comment by wkgcass** [comment]
新release已发布

https://github.com/wkgcass/hotta-pc-assistant/releases/tag/1.0.0
