### ISSUE TITLE
请问测试服一直卡在要更新游戏怎么解决

### ISSUE THREAD

**Issue by lihongyang18792284136** [wkgcass/hotta-pc-assistant#4]
如题 x掉之后重启也没啥用 不知道咋弄了

**Comment by wkgcass** [comment]
1. 需要用特定版本的测试服包
2. 启动后检查hosts配置是否存在127.0.0.1 htcdn.xxxx的记录
3. 需要确保ca证书已添加

**Comment by wkgcass** [comment]
4 months since last reply. closing
